### ISSUE TITLE
Build error possibly related to missing environment variables

### ISSUE THREAD

**Issue by rsreese** [MaxLeiter/maxleiter.com#76]
Seeing an error related to `Error: Missing env vars SUPABASE_URL or SUPABASE_ANON_KEY`. Is it possible to build without defining these variables? If not, what functionality is Supabase providing?

Is the `ELIFECYCLE` error at the end of the output below related or a separate issue?

```
$ pnpm build

> blog@1.0.0 build /Desktop/maxleiter.com
> concurrently "pnpm:build-*"

[rss]
[rss] > blog@1.0.0 build-rss /Desktop/maxleiter.com
[rss] > ts-node --project ./node.tsconfig.json scripts/rss
[rss]
[next]
[next] > blog@1.0.0 build-next /Desktop/maxleiter.com
[next] > next build
[next]
[next] - warn You have enabled experimental features (optimizeCss, mdxRs) in next.config.mjs.
[next] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[next]
[next] - info Creating an optimized production build...
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
[rss] marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
[rss] pnpm run build-rss exited with code 0
[next] - warn Compiled with warnings
[next]
[next] ./node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js
[next] Module not found: Can't resolve 'encoding' in '/Desktop/maxleiter.com/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib'
[next]
[next] Import trace for requested module:
[next] ./node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js
[next] ./node_modules/.pnpm/cross-fetch@3.1.8/node_modules/cross-fetch/dist/node-ponyfill.js
[next] ./node_modules/.pnpm/@supabase+supabase-js@2.21.0/node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
[next] ./node_modules/.pnpm/@supabase+supabase-js@2.21.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
[next] ./node_modules/.pnpm/@supabase+supabase-js@2.21.0/node_modules/@supabase/supabase-js/dist/main/index.js
[next] ./app/lib/supabase/public.ts
[next] ./app/components/ie-or-css/index.tsx
[next]
[next] - info Linting and checking validity of types...
[next] - info Collecting page data...
[next] - warn Using edge runtime on a page currently disables static generation for that page
[next] - info Generating static pages (0/32)
[next] Error: Missing env vars SUPABASE_URL or SUPABASE_ANON_KEY
[next]     at 81624 (/Desktop/maxleiter.com/.next/server/app/(subpages)/ie-or-css3/page.js:450:11)
[next]     at __webpack_require__ (/Desktop/maxleiter.com/.next/server/webpack-runtime.js:25:43)
[next]     at M (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[next]     at ia (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:89)
[next]     at jg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:497)
[next]     at Z (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
[next]     at kg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
[next]     at mg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)
[next]     at Z (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:350)
[next]     at kg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
[next]
[next] Error occurred prerendering page "/ie-or-css3". Read more: https://nextjs.org/docs/messages/prerender-error
[next] Error: Missing env vars SUPABASE_URL or SUPABASE_ANON_KEY
[next]     at 81624 (/Desktop/maxleiter.com/.next/server/app/(subpages)/ie-or-css3/page.js:450:11)
[next]     at __webpack_require__ (/Desktop/maxleiter.com/.next/server/webpack-runtime.js:25:43)
[next]     at M (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:24:46)
[next]     at ia (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js:21:89)
[next]     at jg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:122:497)
[next]     at Z (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
[next]     at kg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
[next]     at mg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)
[next]     at Z (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:350)
[next]     at kg (/Desktop/maxleiter.com/node_modules/.pnpm/next@13.4.19_react-dom@18.3.0-canary-d900fadbf-20230929_react@18.3.0-canary-d900fadbf-20230929/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
[next] - info Generating static pages (8/32)
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3F5:7678:3AEB3:77F1F:651AE3CA.
[next] Time 9.420743
[next] Time 52.308308
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3D7:4133:37525:708E4:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3F1:2C8E:425D0:86995:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3DA:5359:32891A:66629D:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3F2:632F:3CECA:7BCE1:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3ED:2FC1:2F27C:60426:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3F0:21C2:43CA4:89AD9:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3EE:6DB5:39744:751A4:651AE3CB.
[next] Rate limited or error: API rate limit exceeded for 174.172.220.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) If you reach out to GitHub Support for help, please include the request ID F3EF:24C4:34739:6AFD3:651AE3CB.
[next] - info Generating static pages (16/32)
[next] - info Generating static pages (24/32)
[next] - info Generating static pages (32/32)
[next]
[next] > Export encountered errors on following paths:
[next] 	/(subpages)/ie-or-css3/page: /ie-or-css3
[next]  ELIFECYCLE  Command failed with exit code 1.
[next] pnpm run build-next exited with code 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by MaxLeiter** [comment]
I should probably remove supabase, its used for recording views and an interactive page. You can safely remove it and its references without worrying too much. The logs are telling you the usage is in `ie-or-css3`; you should remove that file.
